name: Run Pytest and Generate Coverage Report

# Trigger manually via GitHub Actions UI or on push to master/main
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-cov requests-mock

      # Run pytest with coverage
      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          pytest --cov=task --cov-report=xml --junitxml=report.xml

      # Upload coverage and test result artifacts
      - name: Upload test results and coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            coverage.xml
            report.xml
          retention-days: 7

      # Display completion message
      - name: Finalize
        if: success()
        run: |
          echo "Tests, coverage report, and artifacts uploaded."
